### ISSUE TITLE
Navbar na stronie logowania

### ISSUE THREAD

**Issue by jakub-piecuch** [Driving-School-Manager/angular-demo#5]
Jeszcze jakoś inaczej musimy do tego podejść bo teraz mamy wszędzie, łącznie ze stroną logowania nav bar po lewej :D
![image](https://user-images.githubusercontent.com/49131826/228504960-79833e72-b8d8-4cf8-8847-a2bf9f9333a0.png)

**Comment by Jakub112358** [comment]
Wydaje mi się, że można to tak zrobić, że navbar będzie sobie wołał o rolę i zależnie od wyniku będzie: wyświetłał jedno menu dla admina, wyświetlał drugie menu dla użytkownika z kursem, wyświetlał trzecie menu dla użytkownika zalogowanego bez kursu, nie wyświetlał nic (chował się) dla niezalogowanego użytkownika

**Comment by jakub-piecuch** [comment]
Może pasowałoby zrobić jeden model dla użytkownika zamiast robić osobno kursantów/adminów/instruktorów, który bedzie mial stosowne pole dla roli i jakiegoś enuma zrobić ktory definiuje te role?

**Comment by Jakub112358** [comment]
to jest chyba właśnie pole do dziedziczenia i kursant/admin/instruktor powinni dziedziczyć po użytkowniku

**Comment by jakub-piecuch** [comment]
wykluczyłem ten ruting strony logowania przy użyciu ngIf na nowym branchu pusha zrobiłem
